name: release

on:
  release:
    types: [published]

jobs:
  artifact:
    strategy:
      fail-fast: false
      matrix:
        service: [ archetypes ]
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      pull-requests: write # needed for comment updates
      security-events: write

    steps:
      - name: Git Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        with:
          cache-read-only: false

      - name: Build Java artifact
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: ./gradlew ${{ matrix.service }}:clean ${{ matrix.service }}:build

      - name: Get the version
        id: version
        run: echo VERSION=$(echo $GITHUB_REF | cut -d / -f 3) >> $GITHUB_OUTPUT
