name: Update Gradle Wrapper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        if: ${{ github.event_name != 'pull_request_target' }}
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 #v4.2.1
        with:
          fetch-depth: 0

      - name: Install Java
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 #v4.3.0
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'gradle'

      - name: Update Gradle Wrapper
        # **WARN**: as this action comes from the org without public members,
        # and it has relatively few "stars", so this specific SHA passed #infosec
        # review from SumUp. Please do NOT upgrade this version unless it is
        # incompatible with our build - then we'll have to review the version
        # diff.
        uses: gradle-update/update-gradle-wrapper-action@0407394b9d173dfc9cf5695f9f560fef6d61a5fe #v1.0.20
        with:
          repo-token: ${{ secrets.GH_ACTIONS_PAT }}
